### ISSUE TITLE
Error on Ubuntu 20.10

### ISSUE THREAD

**Issue by hyphone** [Baldomo/asusctltray#1]
Hi there and thank you very much for your work!

Under Ubuntu 20.10 I get this when I want to right click on the icon:

```
Traceback (most recent call last):
  File "/usr/local/bin/asusctltray", line 77, in rightclick
    self.get_current_graphics()
  File "/usr/local/bin/asusctltray", line 134, in get_current_graphics
    res = proxy.call_sync("Vendor", None, Gio.DBusCallFlags.NO_AUTO_START, 2000, None)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Unknown object '/org/asuslinux/Gfx' (41)
Traceback (most recent call last):
  File "/usr/local/bin/asusctltray", line 77, in rightclick
```

**Comment by hyphone** [comment]
sorry my fault - had a faulty configuration
