### ISSUE TITLE
Not launching on Hyprland

### ISSUE THREAD

**Issue by k2helix** [Baldomo/asusctltray#22]
I installed asusctltray on Hyprland (wayland) and I'm getting this error whenever I try to open asusctltray from the command line (desktop app also does not work)

```
Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/asusctltray", line 690, in <module>
    TrayIcon(loop)
  File "/usr/local/bin/asusctltray", line 650, in __init__
    self.build_menu()
  File "/usr/local/bin/asusctltray", line 663, in build_menu
    PowerProfilesController().attach(self.menu)
  File "/usr/local/bin/asusctltray", line 328, in attach
    for item in self.items:
                ^^^^^^^^^^
  File "/usr/local/bin/asusctltray", line 585, in items
    for p in self.proxy.Get("net.hadess.PowerProfiles", "Profiles")
             ^^^^^^^^^^
  File "/usr/local/bin/asusctltray", line 591, in proxy
    dbus.SystemBus().get_object(
  File "/usr/lib64/python3.12/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.12/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

**Comment by Baldomo** [comment]
The DBus API for fan profiles has been substantially changed on asusctl's side, I am already working on a fix for the latest asusctl version. It will break compatibility with old versions but oh well, I can't maintain this program  for that many old API versions

**Comment by Baldomo** [comment]
I generally fixed the script in c8ef0ba according to the DBus API changes. However, looking at the stacktrace you posted, it may just be that you're missing `power-profiles-daemon` or it's not launching correctly (it must be enabled in systemd of course). Please do let me know if everything works now.

Sorry for the wait!

**Comment by k2helix** [comment]
Hi, you're right, I don't have the power-profiles-daemon installed because I use tlp. Will let you know if it works when I get to configure Hyprland again. Thanks for your help

**Comment by K-Zawis** [comment]
Very similar issue but slightly different message. 

Also experiencing this when trying to run via terminal on Hyprland (wayland). Running the desktop shortcut fails silently (nothing happens). 

I had `tuneD` instead of `power-profiles-daemon`, but experience the same exact error after switching to `power-profiles-daemon` and rebooting. However I do see that the error messages are different pointing at different issues.

I'd imagine this is related to what you said earlier?:
> The DBus API for fan profiles has been substantially changed on asusctl's side  

 `asusd` is active and running just fine on my system but not sure if this is potentially something on my end, rather than related to the original issue.

```
× asusctltray
Traceback (most recent call last):
  File "/usr/lib64/python3.13/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              BUS_DAEMON_IFACE, 'GetNameOwner',
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              's', (bus_name,))
                              ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
        message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/asusctltray", line 736, in <module>
    TrayIcon(loop)
    ~~~~~~~~^^^^^^
  File "/usr/local/bin/asusctltray", line 693, in __init__
    self.build_menu()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/bin/asusctltray", line 709, in build_menu
    CPUProfileController().attach(self.menu)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/local/bin/asusctltray", line 340, in attach
    menu_item.set_active(item == self.active_item)
                                 ^^^^^^^^^^^^^^^^
  File "/usr/local/bin/asusctltray", line 487, in active_item
    data = self.proxy.FanCurveData(profile_index)
           ^^^^^^^^^^
  File "/usr/local/bin/asusctltray", line 475, in proxy
    dbus.SystemBus().get_object("org.asuslinux.Daemon", "/org/asuslinux"),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 introspect=introspect,
                                 ^^^^^^^^^^^^^^^^^^^^^^
                                 follow_name_owner_changes=follow_name_owner_changes)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     BUS_DAEMON_IFACE,
                                     ^^^^^^^^^^^^^^^^^
                                     'StartServiceByName',
                                     ^^^^^^^^^^^^^^^^^^^^^
                                     'su', (bus_name, flags)))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
        message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

**Comment by flukejones** [comment]
I have very heavily changed things to match what I have been doing with kernel and enabling new RGB devices. Please follow the below.

![Image](https://github.com/user-attachments/assets/815f6364-840f-40e6-acd9-28590e33214b)
![Image](https://github.com/user-attachments/assets/ed53d740-44d6-4d8e-8ea8-5fb570f87ca8)
![Image](https://github.com/user-attachments/assets/f43e3c20-c8fe-4d33-83e7-c58f5078d4ff)

**Comment by K-Zawis** [comment]
Thanks a lot. 

I switched out the corresponding dbus info in the script and it now runs as expected.

**Comment by mathimino** [comment]
I'm sorry but I'm a newbie and have no idea how to apply the fix. I have the same error message has @K-Zawis and I have installed asusctltray from the AUR.

**Comment by webbrain-one** [comment]
Hi! Thanks for the detailed report. I’ve opened a pull request to address this: #30. The fix gracefully handles cases where the `net.hadess.PowerProfiles` D-Bus service isn't available or activatable, preventing the crash and allowing `asusctltray` to launch normally on Hyprland and other Wayland setups. Let me know if it resolves the issue for you! Thanks again for your help. 🙌
