### ISSUE TITLE
Not launching on ArchLinux {UX6404VV}

### ISSUE THREAD

**Issue by CyberFazaN** [Baldomo/asusctltray#24]
Can't launch due to an error. Installed from AUR (asusctltray-git )

```
╭─ ~ 
╰─❯ asusctltray 
Traceback (most recent call last):
  File "/usr/local/bin/asusctltray", line 736, in <module>
    TrayIcon(loop)
  File "/usr/local/bin/asusctltray", line 693, in __init__
    self.build_menu()
  File "/usr/local/bin/asusctltray", line 709, in build_menu
    CPUProfileController().attach(self.menu)
  File "/usr/local/bin/asusctltray", line 340, in attach
    menu_item.set_active(item == self.active_item)
                                 ^^^^^^^^^^^^^^^^
  File "/usr/local/bin/asusctltray", line 487, in active_item
    data = self.proxy.FanCurveData(profile_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownInterface: Unknown interface 'org.asuslinux.FanCurves'
```

**Comment by CyberFazaN** [comment]
Closing the issue. asusctl dosen't support profile switching on my laptop yet.

```
Starting version 6.0.11
Profiles not supported by either this kernel or by the laptop.

Error: Not supported

asusctl version: 6.0.11
 Product family: Zenbook
     Board name: UX6404VV

Supported interfaces:

[
    "org.asuslinux.Platform",
]

Supported properties on Platform:

[
    ChargeControlEndThreshold,
    GpuMuxMode,
]
```
