### ISSUE TITLE
DBusException error

### ISSUE THREAD

**Issue by LittleCannon** [Baldomo/asusctltray#7]
Hi,
After update of asusctl (and installing supercgfxctl) and then updating asusctltray, I receive this error upon starting asusctltray:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.hadess.PowerProfiles': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/asusctltray", line 333, in <module>
    TrayIcon()
  File "/usr/local/bin/asusctltray", line 93, in __init__
    bus.get_object("net.hadess.PowerProfiles", "/net/hadess/PowerProfiles"),
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name net.hadess.PowerProfiles was not provided by any .service files
```

Did I miss something?

**Comment by LittleCannon** [comment]
I did miss something.
Installing power-profile-daemon solved issue.

**Comment by Baldomo** [comment]
Yeah the actual error was described in the last line of your log:
```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name net.hadess.PowerProfiles was not provided by any .service files
```
Which is systemd's overly cryptic way of saying that a service cannot be found, mainly because a certain program is not installed or has not provided its own service file.
