### ISSUE TITLE
Does not install in ubuntu No such file or directory: '/etc/supergfxd.conf'

### ISSUE THREAD

**Issue by guysoft** [Baldomo/asusctltray#8]
Hey, install:
```
asusctltray$ sudo bash -x ./install.sh 
+ ((  EUID != 0  ))
+ cp asusctltray /usr/local/bin
+ chmod a+x /usr/local/bin/asusctltray
+ cp asusctltray.svg /usr/share/pixmaps
+ cp asusctltray.desktop /usr/share/applications
```
After running I get:
```python3
$ asusctltray 
Traceback (most recent call last):
  File "/usr/local/bin/asusctltray", line 333, in <module>
    TrayIcon()
  File "/usr/local/bin/asusctltray", line 84, in __init__
    with open(GFX_CONF, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/supergfxd.conf'
```

Versions
```
$ asusctl --version

App and daemon versions:
     asusctl v3.5.1
       asusd v3.7.2

Component crate versions:
   rog-anime v1.0.5
    rog-aura v1.1.0
    rog-dbus v3.5.1
rog-profiles v0.1.2
   rog-types v3.2.0
```

**Comment by Baldomo** [comment]
Do you have `supergfxctl` installed and working correctly?

**Comment by guysoft** [comment]
Ok, I had to install ``supergfxctl`` and then to enable it.
and also ``apt-get install power-profiles-daemon``

That solves the issue.
